apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactivechaindb
  namespace: reactivechaindb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactivechaindb
  template:
    metadata:
      labels:
        app: reactivechaindb
    spec:
      containers:
        - name: reactivechaindb
          image: namanoncode/reactivechaindbv1:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:27017/bigchain"

            - name: BIGCHAINDB_API_URL
              value: "http://bigchaindb:9984"

            - name: SPRING_DATA_REDIS_HOST
              value: "redis"

            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: reactivechaindb
  namespace: reactivechaindb
spec:
  selector:
    app: reactivechaindb
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

